-- Initial database schema for D STUDIOS
CREATE TABLE IF NOT EXISTS products (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	category VARCHAR(100) NOT NULL,
	price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	description TEXT,
	image_url VARCHAR(500),
	video_url VARCHAR(500),
	gumroad_url VARCHAR(500),
	developer_name VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_ratings (
	id INT AUTO_INCREMENT PRIMARY KEY,
	product_id INT NOT NULL,
	rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
	comment TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);
